# Generated by Django 6.0 on 2026-06-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='commission_percent',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='delivery_share_percent',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
