# Generated by Django 6.0 on 2026-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_agent_latitude_order_agent_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
    ]
